# Generated by Django 5.1.4 on 2024-12-22 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.vendor_profile'),
        ),
        migrations.AddField(
            model_name='featuredproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='services.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.vendor_profile'),
        ),
        migrations.AddField(
            model_name='userproductinteraction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.product'),
        ),
        migrations.AddField(
            model_name='userproductinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='featuredproduct',
            index=models.Index(fields=['date_featured'], name='services_fe_date_fe_31ad45_idx'),
        ),
        migrations.AddConstraint(
            model_name='featuredproduct',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_featured_product'),
        ),
        migrations.AddIndex(
            model_name='userproductinteraction',
            index=models.Index(fields=['user'], name='services_us_user_id_8afbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='userproductinteraction',
            index=models.Index(fields=['product'], name='services_us_product_b25eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='userproductinteraction',
            index=models.Index(fields=['timestamp'], name='services_us_timesta_cd143e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userproductinteraction',
            unique_together={('user', 'product', 'interaction_type')},
        ),
    ]
