# Generated by Django 5.1.4 on 2024-12-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('used_good', 'used - Good Condition'), ('used_excellent', 'used - Excellent Condition'), ('Brand_new', ' Brand New')], default='brand_new', max_length=20),
        ),
    ]
